language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t zethembiso/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true zethembiso/docker-react npm run test